### ISSUE TITLE
Passing Task Outputs to Task Inputs Files not found

### ISSUE THREAD

**Issue by predatorian3** [starkandwayne/concourse-tutorial#181]
While following the [Passing Task Outputs to Task Inputs](https://concoursetutorial.com/basics/task-outputs-to-inputs/) tutorial, I am getting the error

```
files not found
```

After the image pulls down and inputs are copied to the container. From what I'm seeing, the file should be right where the tutorial is saying it is. All of the other examples have worked up until this point. 

```
version: '3'
services:
  concourse-db:
    # https://hub.docker.com/_/postgres/
    image: postgres:11
    environment:
      - "POSTGRES_DB=concourse"
      - "POSTGRES_PASSWORD=concourse_pass"
      - "POSTGRES_USER=concourse_user"
      - "PGDATA=/database"
  concourse:
    # https://hub.docker.com/r/concourse/concourse/
    image: concourse/concourse:4.2.2
    command: quickstart
    privileged: true
    depends_on:
      - "concourse-db"
    ports:
      - "8080:8080"
    environment:
      - "CONCOURSE_POSTGRES_HOST=concourse-db"
      - "CONCOURSE_POSTGRES_USER=concourse_user"
      - "CONCOURSE_POSTGRES_PASSWORD=concourse_pass"
      - "CONCOURSE_POSTGRES_DATABASE=concourse"
      - "CONCOURSE_EXTERNAL_URL=https://mycomputer.company.net"
      - "CONCOURSE_ADD_LOCAL_USER=test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW"
      - "CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true"
      - "CONCOURSE_WORKER_GARDEN_NETWORK"
```

Just using the `docker-compose.yml` from the concourse/concourse-docker repo.
