### ISSUE TITLE
Hello World tutorial errors with base resource type not found: docker-image

### ISSUE THREAD

**Issue by chibby0ne** [starkandwayne/concourse-tutorial#243]
As the title suggests, the Hello World tutorial fails.

Steps to reproduce:

1. Start concourse using docker-compose.

```
$ wget https://raw.githubusercontent.com/starkandwayne/concourse-tutorial/master/docker-compose.yml
$ docker-compose up -d
```

2. Execute the Hello World task and have the error:

```
$ git clone https://github.com/starkandwayne/concourse-tutorial.git
$ cd concourse-tutorial/tutorials/basic/task-hello-world
$ fly -t tutorial execute -c task_hello_world.yml
executing build 1 at http://127.0.0.1:8080/builds/1
initializing
create resource config: base resource type not found: docker-image
create resource config: base resource type not found: docker-image
errored
```

The task contents is:

```
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: echo
  args: [hello world]
```

Software versions:
Arch Linux
Docker version 20.10.6, build 370c28948e
docker-compose version 1.29.2, build unknown
Fly version: 7.3.1

**Comment by chibby0ne** [comment]
I've also tried it with the `image_resource.type: registry-image` and I get a similar error of:
```
create resource config: base resource type not found: registry-image
```

**Comment by adamcadaver** [comment]
I believe this is because you are running on an arch architecture not x86_64 as described here: https://github.com/docker/for-mac/issues/5547

According to that ticket you should be able to replace change your `docker-compose.yml` to 
```yml
  concourse:
    image: rdclda/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      - CONCOURSE_POSTGRES_HOST=concourse-db
      - CONCOURSE_POSTGRES_USER=concourse_user
      - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL
      - CONCOURSE_ADD_LOCAL_USER=admin:admin
      - CONCOURSE_MAIN_TEAM_LOCAL_USER=admin
```

But I tried that and I didn't work :(
