### ISSUE TITLE
10 deploy app readme? 

### ISSUE THREAD

**Issue by longnguyen11288** [starkandwayne/concourse-tutorial#3]
What does a "credentials.yml" looks like?

**Comment by benmoss** [comment]
```yml
cf-username: username
cf-password: password
cf-organization: username-org
cf-space: development
```
