### ISSUE TITLE
Example 05 fails to do resource check on Docker

### ISSUE THREAD

**Issue by code-4-fun** [starkandwayne/concourse-tutorial#45]
I tried Example 5 [**05_pipeline_task_hello_world**] and it fails with following error;

resource script '/opt/resource/check []' failed: exit status 1
stderr:
failed to ping registry: 2 error(s) occurred:
- ping https: Get https://registry-1.docker.io/v2: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
- ping http: Get https://registry-1.docker.io/v2: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by drnic** [comment]
Perhaps this is a temporary docker hub issue. I was working thru these
tutorials yesterday and they were ok. That issue should affect each
tutorial equally; other tutorials affected too?

**Comment by yngvark** [comment]
I got this error now on the same tutorial, even though I got it to work first. Here is what I did:

- Installed Concourse (created a docker-compose.yml) according to http://concourse.ci/docker-repository.html
- Ran tutorial at http://concourse.ci/hello-world.html
- Running the hello-world build worked (turned green)
- I adjusted the docker-compose.yml to save the database folder at a specific location, and I put everything on a specific network, like this:


```
version: '2'

services:

  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    volumes:
        - ./database:/database
    networks:
      - concourse

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    ports: ["8081:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "http://127.0.0.1:8081"
      CONCOURSE_POSTGRES_DATA_SOURCE: |
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
    networks:
      - concourse

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
    networks:
      - concourse

networks:
  concourse:

```

- Reran the tutorial and re-created the hello-world pipeline. Now it doesn't work anymore. The build takes 9 min 3 sec before it fails with the following error:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to ping registry: 2 error(s) occurred:

* ping https: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.11:53: read udp 127.0.0.1:33472->127.0.0.11:53: read: connection refused
* ping http: Get http://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.11:53: read udp 127.0.0.1:34950->127.0.0.11:53: read: connection refused
```
- After reverting the docker-compose.yml back to the original, I still get this error.

Any suggestions?
