### ISSUE TITLE
12 - Publishing outputs:  Host key verification failed.

### ISSUE THREAD

**Issue by acca301** [starkandwayne/concourse-tutorial#51]
Walking through the tutorial step-by-step. Made a gist, added

<pre><code> - name: resource-gist
   type: git
   source:
     uri: git@gist.github.com:71c94aad09a4adc12ebec5ac2794bab4.git
     branch: master
</code></pre>

into 12_publishing_outputs/pipeline.yml. A build attempt fails in resource-gist with

> Cloning into '/tmp/build/get'...
> Host key verification failed.
> fatal: Could not read from remote repository.

Note this is pull, we're not at the push stage yet.

The host key is certainly not in ~/.ssh/known_hosts inside the task container. How / where can I run ssh-keyscan or push `known_hosts' there?

**Comment by drnic** [comment]
AK, can I ask a favor? Can you please recreate this ticket with the concourse/git-resource project, link it to this issue and tag me as well (so I get notifications).
I'm sorry I'm not sure I know how to debug/ fix this issue myself.
Nic






On Tue, Jul 5, 2016 at 7:54 AM +1000, "Alexander Kuznetsov" <notifications@github.com> wrote:












Walking through the tutorial step-by-step. Made a gist, added

 - name: resource-gist
   type: git
   source:
     uri: git@gist.github.com:71c94aad09a4adc12ebec5ac2794bab4.git
     branch: master




into 12_publishing_outputs/pipeline.yml. A build attempt fails in resource-gist with




Cloning into '/tmp/build/get'...

Host key verification failed.

fatal: Could not read from remote repository.




Note this is pull, we're not at the push stage yet.



The host key is certainly not in ~/.ssh/known_hosts inside the task container. How / where can I run ssh-keyscan or push `known_hosts' there?

**Comment by acca301** [comment]
Done.
BTW, your tutorial is great - unfortunately there is not many manuals made with such clarity.

**Comment by acca301** [comment]
My bad. `|` was they key.
I usually do chomping with `|-`, thus I wrote it the way:
```yaml
  resources:
  - name: foo
    type: git
    source:
      uri: ...
      private_key: |-
        ---BEGIN BLAH BLAH---
        .....
        ---END BLAH BLAH---
```
while the working syntax is 

```yaml
  resources:
  - name: foo
    type: git
    source:
      uri: ...
      private_key: |
        ---BEGIN BLAH BLAH---
        .....
        ---END BLAH BLAH---
```
